- app/Http/Controllers/Api/GiroComercialCatalogoController.php
- routes/api.php
> CrearGirosApi

- app/Http/Controllers/Api/DescuentoCatalogoController.php
- app/Http/Resources/DescuentoCatalogoResource.php
- app/Models/DescuentoCatalogo.php
- database/migrations/2024_06_28_211105_create_descuento_catalogos_table.php
- routes/api.php
modifcacion de modelo, api y migracion
> CrearApiDescuento

- app/Http/Controllers/Api/Tipo_tomaController.php
- app/Http/Controllers/Api/UsuarioController.php
- app/Http/Requests/StoreTipoTomaRequest.php
- app/Http/Requests/StoreUsuarioMoralRequest.php
- app/Http/Requests/StoreUsuarioRequest.php
- app/Http/Requests/UpdateTipoTomaRequest.php
- app/Http/Requests/UpdateUsuarioMoralRequest.php
- app/Http/Requests/UpdateUsuarioRequest.php
- app/Models/TipoToma.php
- routes/api.php
ya jala tod con shows y con try catch
> Crear usuario api y crear tipoToma api

- app/Http/Controllers/Api/ServicioController.php
- app/Http/Requests/StoreServicioRequest.php
- app/Http/Requests/UpdateServicioRequest.php
- app/Http/Resources/ServicioResource.php
- app/Models/Servicio.php
- database/migrations/2024_07_08_182955_create_servicios_table.php
- routes/api.php
> CrearServiciosApi

- app/Http/Controllers/Api/DatosDomiciliacionController.php
- app/Http/Controllers/Api/MedidorController.php
- app/Http/Controllers/Api/ServicioController.php
- app/Http/Requests/StoreDatosDomiciliacionRequest.php
- app/Http/Requests/UpdateDatosDomiciliacionRequest.php
- app/Http/Resources/DatosDomiciliacionResource.php
- app/Models/DatosDomiciliacion.php
- database/migrations/2024_07_08_211858_create_datos_domiciliados_table.php
- routes/api.php
api domiciliados + correcciones a nombres de variables
> CrearDatosDomiciliados

- app/Http/Controllers/Api/AbonoController.php
- app/Http/Controllers/Api/AjusteCatalagoController.php
- app/Http/Controllers/Api/AnomaliaCatalagoController.php
- app/Http/Controllers/Api/CatalogoBonificacionController.php
- app/Http/Controllers/Api/ConstanciaCatalogoController.php
- app/Http/Controllers/Api/ConvenioController.php
- app/Http/Controllers/Api/DescuentoCatalogoController.php
- app/Http/Controllers/Api/GiroComercialCatalogoController.php
- app/Http/Requests/StoreAbonoRequest.php
- app/Http/Requests/StoreAjusteCatalogoRequest.php
- app/Http/Requests/StoreCargoRequest.php
- app/Http/Requests/StoreConvenioCatalogoRequest.php
- app/Http/Requests/StoreCosntanciaCatalogoRequest.php
- app/Http/Requests/StoreDatosDomiciliacionRequest.php
- app/Http/Requests/StoreDescuentoAsociadoRequest.php
- app/Http/Requests/StoreDescuentoCatalogoRequest.php
- app/Http/Requests/StoreGiroComercialCatalogoRequest.php
- app/Http/Requests/StoreMedidorRequest.php
- app/Http/Requests/StoreServicioRequest.php
- app/Http/Requests/UpdateAbonoRequest.php
- app/Http/Resources/AbonoResource.php
- app/Models/Abono.php
- database/migrations/2024_07_09_165859_create_abonos_table.php
- routes/api.php
> Crear abono api

- app/Http/Controllers/Api/AjusteCatalagoController.php
- app/Http/Controllers/Api/AnomaliaCatalagoController.php
- app/Http/Controllers/Api/ConstanciaCatalogoController.php
- app/Http/Controllers/Api/ConvenioController.php
- app/Http/Controllers/Api/DescuentoCatalogoController.php
- app/Http/Controllers/Api/GiroComercialCatalogoController.php
correcciones a las Apis de restauración
> correccionesApi

- app/Http/Controllers/Api/ContratoController.php
- app/Http/Controllers/Api/Tipo_tomaController.php
- app/Http/Controllers/Api/UsuarioController.php
- app/Http/Requests/StoreContratoRequest.php
- app/Http/Requests/StoreTipoTomaRequest.php
- app/Http/Requests/UpdateContratoRequest.php
- app/Models/Contrato.php
> Folio de solicitud te lo da el sistema

- app/Http/Controllers/Api/correccionInformacionSolicitudController.php
- app/Http/Requests/StorecorreccionInformacionSolicitudRequest.php
- app/Http/Requests/UpdatecorreccionInformacionSolicitudRequest.php
- app/Http/Resources/correccionInformacionSolicitudResource.php
- app/Models/correccionInformacionSolicitud.php
- database/migrations/2024_07_09_211212_create_correccion_informacion_solicitudes_table.php
- routes/api.php
CRUD de solicitud de correcciones todo es nuevo y la ruta queda bien abajo
> SolicitudDeCorreccionesAPI

- app/Http/Controllers/Api/CatalogoBonificacionController.php
- app/Http/Controllers/Api/Tipo_tomaController.php
- app/Http/Requests/StoreCatalogoBonificacionRequest.php
- app/Http/Requests/StoreServicioRequest.php
- app/Http/Requests/StoreTipoTomaRequest.php
- app/Http/Requests/UpdateServicioRequest.php
- app/Http/Resources/ServicioResource.php
- app/Models/Contrato.php
- app/Models/GiroComercialCatalogo.php
- app/Models/Servicio.php
- app/Models/TipoToma.php
- app/Models/Toma.php
- app/Models/Usuario.php
- database/migrations/2024_07_08_160536_create_contratos_table.php
- database/migrations/2024_07_08_165158_create_toma_table.php
- database/migrations/2024_07_08_182955_create_servicios_table.php
> Relaciones modelos

- database/factories/ConceptoCatalogoFactory.php
- database/seeders/AnomaliaSeeder.php
- database/seeders/BonificacionCatalogoSeeder.php
- database/seeders/ConceptoCatalogoSeeder.php
- database/seeders/ConvenioSeeder.php
Seeder del catalogo de conceptos
> SeederCatalogoConceptos

- app/Http/Requests/StoreAjusteCatalogoRequest.php
- app/Http/Requests/StoreCatalogoBonificacionRequest.php
- app/Http/Requests/StoreConvenioCatalogoRequest.php
- app/Http/Requests/StoreDescuentoCatalogoRequest.php
- app/Http/Requests/UpdateAjusteCatalogoRequest.php
- app/Http/Requests/UpdateCatalogoBonificacionRequest.php
- app/Http/Requests/UpdateConvenioCatalogoRequest.php
- app/Http/Requests/UpdateDescuentoCatalogoRequest.php
- app/Http/Resources/AjusteCatalogoResource.php
- app/Http/Resources/CatalogoBonificacionResource.php
- app/Http/Resources/ConvenioResource.php
- app/Http/Resources/DescuentoCatalogoResource.php
- app/Models/AjusteCatalogo.php
- app/Models/CatalogoBonificacion.php
- app/Models/ConvenioCatalogo.php
- app/Models/DescuentoCatalogo.php
- app/Models/Medidor.php
- app/Models/TipoToma.php
- app/Models/Toma.php
- database/migrations/2024_06_28_195616_create_ajuste_catalogos_table.php
- database/migrations/2024_06_28_211105_create_descuento_catalogos_table.php
- database/migrations/2024_07_01_190045_create_convenio_catalogos_table.php
- database/migrations/2024_07_03_191501_create_catalogo_bonificaciones_table.php
> RelacionesModelos2

- app/Http/Requests/StoreAnomaliaCatalogoRequest.php
- app/Http/Requests/StoreConceptoCatalogoRequest.php
- app/Http/Requests/UpdateConceptoCatalogoRequest.php
- app/Models/ConceptoCatalogo.php
- database/migrations/2024_06_28_195601_create_anomalia_catalogos_table.php
- database/migrations/2024_07_01_152935_create_concepto_catalogos_table.php
- database/seeders/AjusteSeeder.php
- database/seeders/BonificacionCatalogoSeeder.php
- database/seeders/ConceptoCatalogoSeeder.php
- database/seeders/ConvenioSeeder.php
- database/seeders/DatabaseSeeder.php
Seeders de los catalogos basicos
> SeedersDeCatalogos

- app/Http/Controllers/Api/cargoDirectoController.php
- routes/api.php
> cargoDirectoFix

- app/Models/AjusteCatalogo.php
- app/Models/ConceptoAplicable.php
- app/Models/ConvenioCatalogo.php
- app/Models/Descuento.php
- app/Models/DescuentoAsociado.php
- app/Models/DescuentoCatalogo.php
- app/Models/Pago.php
- database/migrations/2024_07_08_165158_create_toma_table.php
- database/migrations/2024_07_15_181037_create_pagos_table.php
- database/migrations/2024_07_15_181805_create_descuentos_table.php
- database/migrations/2024_07_15_192420_create_concepto_aplicables_table.php
> Crear pagos

- app/Http/Resources/ConceptoResource.php
> falto prioridad abono

- app/Http/Controllers/Api/CalleController.php
- app/Http/Controllers/Api/ColoniaController.php
- app/Http/Requests/StoreCalleRequest.php
- app/Http/Requests/StoreColoniaRequest.php
- app/Http/Requests/UpdateCalleRequest.php
- app/Http/Requests/UpdateColoniaRequest.php
- app/Http/Resources/CalleResource.php
- app/Http/Resources/ColoniaResource.php
- app/Models/Calle.php
- app/Models/Colonia.php
- database/factories/CalleFactory.php
- database/factories/ColoniaFactory.php
- database/migrations/2024_07_16_201047_create_calles_table.php
- database/migrations/2024_07_16_205154_create_colonias_table.php
- database/seeders/TomaSeeder.php
- routes/api.php
> calleColoniaApi

- database/seeders/DatabaseSeeder.php
- database/seeders/TipoTomasSeeder.php
> Sedeer tipo toma

- app/Http/Requests/StoreAbonoRequest.php
- app/Http/Requests/UpdateAbonoRequest.php
- app/Http/Resources/AbonoResource.php
- app/Models/Abono.php
- app/Models/Cargo.php
- app/Models/Contrato.php
- app/Models/cargoDirecto.php
- app/Providers/AppServiceProvider.php
- database/factories/AbonoFactory.php
- database/factories/CargoFactory.php
- database/factories/ConceptoAplicableFactory.php
- database/factories/ContratoFactory.php
- database/factories/DescuentoCatalogoFactory.php
- database/factories/OperadorFactory.php
- database/factories/PagoFactory.php
- database/migrations/2024_07_09_162647_create_cargos_table.php
- database/migrations/2024_07_09_165859_create_abonos_table.php
- database/seeders/DescuentosSeeder.php
- database/seeders/UsuarioSeeder.php
> Mas factorys

- app/Http/Controllers/Api/TarifaController.php
- app/Http/Requests/StoreCargoRequest.php
- app/Http/Requests/UpdateCargoRequest.php
- app/Http/Resources/CargoResource.php
- app/Models/Cargo.php
- app/Models/ConceptoCatalogo.php
- app/Models/Factibilidad.php
- database/factories/CargoFactory.php
- database/factories/ContratoFactory.php
- database/factories/CotizacionDetalleFactory.php
- database/factories/CotizacionFactory.php
- database/factories/FactibilidadFactory.php
- database/factories/TarifaConceptoDetalleFactory.php
- database/factories/TarifaServiciosDetalleFactory.php
- database/migrations/2024_07_08_182252_create_factibilidads_table.php
- database/migrations/2024_07_09_162647_create_cargos_table.php
- database/seeders/ConceptoCatalogoSeeder.php
- database/seeders/DatabaseSeeder.php
- database/seeders/TipoTomaSeeder.php
- database/seeders/TomaSeeder.php
- database/seeders/UsuarioSeeder.php
> Factibilidad cotizacion factory

- app/Http/Controllers/Api/CajasController.php
- app/Http/Requests/StoreCajasRequest.php
- app/Http/Requests/UpdateCajasRequest.php
- app/Http/Resources/CajaResource.php
- app/Models/Caja.php
- app/Models/Pago.php
- app/Models/corteCaja.php
- app/Models/fondoCaja.php
- app/Models/retiroCaja.php
- database/migrations/2024_07_17_191022_create_cajas_table.php
- database/migrations/2024_07_18_172724_create_fondo_cajas_table.php
- database/migrations/2024_07_18_172737_create_retiro_cajas_table.php
- database/migrations/2024_07_18_172756_create_corte_cajas_table.php
- routes/api.php
> relacionCajas

- database/factories/PagoFactory.php
- database/migrations/2024_07_18_172737_create_retiro_cajas_table.php
- database/migrations/2024_07_18_172756_create_corte_cajas_table.php
> relacionCajasFix

- app/Http/Requests/StoreTarifaConceptoDetalleRequest.php
- app/Http/Resources/TarifaConceptoDetalleResource.php
- app/Http/Resources/TarifaResource.php
- app/Models/Pago.php
- app/Models/TarifaConceptoDetalle.php
- app/Models/Toma.php
- app/Models/tarifa.php
- database/factories/AjusteCatalogoFactory.php
- database/factories/ContratoFactory.php
- database/factories/CotizacionFactory.php
- database/factories/DatosDomiciliacionFactory.php
- database/factories/PagoFactory.php
- database/factories/TarifaConceptoDetalleFactory.php
- database/seeders/AjusteSeeder.php
- database/seeders/DescuentosSeeder.php
> Ultimos seeders

- app/Http/Controllers/Api/TarifaController.php
- routes/api.php
se agrego una nueva ruta un metodo, y se modifico el metodo de update de tarifa.
> modificacion metodo tarifa

- app/Models/Consumo.php
- app/Models/Lectura.php
- app/Models/Toma.php
- database/migrations/2024_07_22_211100_create_consumos_table.php
- database/migrations/2024_07_23_161138_create_lecturas_table.php
Migracion, modelo y relaciones de consumo y lectura
> consumoYLecturaMigracionModelo

- app/Models/Libro.php
- app/Models/Periodo.php
- app/Models/Ruta.php
- database/factories/LibroFactory.php
- database/factories/PeriodoFactory.php
- database/factories/RutaFactory.php
- database/migrations/2024_07_24_152139_create_libros_table.php
- database/seeders/DatabaseSeeder.php
- database/seeders/LibroSeeder.php
- database/seeders/RutaSeeder.php
> relacionPeriodo

- app/Http/Controllers/Api/ContactoController.php
- app/Http/Requests/StoreContactoRequest.php
- app/Http/Requests/UpdateContactoRequest.php
- app/Http/Resources/ContactoResource.php
- app/Models/Contacto.php
- app/Models/DatoFiscal.php
- database/migrations/2024_07_25_204910_create_contactos_table.php
- routes/api.php
> ContactoAPI

- app/Http/Controllers/Api/CajasController.php
- app/Http/Controllers/Api/TomaController.php
- app/Models/Cargo.php
- app/Models/Contrato.php
- app/Models/Pago.php
- app/Models/Toma.php
- app/Models/Usuario.php
- app/Providers/AppServiceProvider.php
- database/factories/CargoFactory.php
- database/factories/OrdenTrabajoCatalogoFactory.php
- database/factories/OrdenTrabajoConfiguracionFactory.php
- database/factories/PagoFactory.php
- database/migrations/2024_07_15_181037_create_pagos_table.php
- database/seeders/ConceptoCatalogoSeeder.php
- database/seeders/DatabaseSeeder.php
- database/seeders/OrdenesTrabajo.php
- database/seeders/OrdenesTrabajoSeeder.php
- routes/api.php
> Mas seeders

- app/Models/Caja.php
- app/Models/CajaCatalogo.php
- app/Models/Operador.php
- app/Models/OperadorAsignado.php
- database/factories/CajaCatalogoFactory.php
- database/factories/CajaFactory.php
- database/factories/OperadorAsignadoFactory.php
- database/migrations/2024_07_30_165916_create_caja_catalogos_table.php
- database/migrations/2024_07_30_172039_create_operador_asignados_table.php
- database/seeders/CajaCatalogoSeeder.php
- database/seeders/DatabaseSeeder.php
- database/seeders/OperadorAsignadoSeeder.php
catalogo de cajas, operadores asignados y seeders
> catalogoCajas

- app/Http/Controllers/Api/UsuarioController.php
- app/Services/UsuarioService.php
- routes/api/usuarios/usuario.php
Cambio de los métodos de usuarioController a UsuarioService
> UsuarioServiceAPI

- app/Http/Requests/StoreCajasRequest.php
- app/Http/Requests/UpdateCajasRequest.php
- app/Http/Resources/CorteCajaResource.php
- app/Http/Resources/FondoCajaResource.php
- app/Models/CorteCaja.php
- app/Models/FondoCaja.php
- app/Services/Caja/CajaService.php
- database/migrations/2024_07_18_172724_create_fondo_cajas_table.php
- database/migrations/2024_07_18_172756_create_corte_cajas_table.php
Migraciones y modelos de cajas, fondo y corte de cajas
> CajasAPIVer2

- app/Models/Convenio.php
- app/Models/Toma.php
- app/Models/Usuario.php
- app/Services/AtencionUsuarios/ConvenioService.php
- database/migrations/2024_09_02_185145_create_convenios_table.php
Relaciones y condiciones que evitan el registro de mas de un convenio activo en el mismo usuario/toma
> ConvenioUnicoAPI

- app/Http/Controllers/Api/ConvenioController.php
- app/Http/Requests/StoreConvenioRequest.php
- app/Services/AtencionUsuarios/ConvenioService.php
Registra convenios pero aun faltan los cargos de las letras
> RegistrarConveniosVer1

- app/Http/Controllers/Api/ConvenioController.php
- app/Services/AtencionUsuarios/ConvenioService.php
- routes/api/catalogos/convenio.php
Base de cancelación de convenios y registro de convenios finalizado
> ConvenioVer4

- app/Http/Controllers/Api/ConvenioController.php
- app/Services/AtencionUsuarios/ConvenioService.php
- routes/api/catalogos/convenio.php
Api para consultar convenios activos con sus letras
> ConsultarConvenioApi

- app/Services/AtencionUsuarios/ConvenioService.php
Se updateo para que meta el catalogo de ocnvenio en la consulta
> ConsultarConvenioUpdate

- app/Services/AtencionUsuarios/ConvenioService.php
Cancelacion de convenio funciona, el servicio aun necesita validaciones y mensajes de error mas claros
> ConvenioVer5Api

- app/Models/Toma.php
- app/Services/AtencionUsuarios/ConvenioService.php
Validaciones en caso de errores al ingresar informacion.
> ValidacionesGeneralesConveniosService

- app/Services/AtencionUsuarios/ConvenioService.php
Solucion al error que provoca diferencia en los suma de los pagos de las letras con respecto al pago total
> RegistrarConveniosBugCentavosLetrasFix

- app/Http/Controllers/Api/ConvenioController.php
- app/Services/AtencionUsuarios/ConvenioService.php
- routes/api/catalogos/convenio.php
Api que obtiene todos los registros de convenios, con sus letras y su registro asociado en el catalogo de convenios.
> ConsultarListaConvenioApi

- app/Http/Requests/StoreDescuentoAsociadoRequest.php
- app/Services/AtencionUsuarios/DescuentoAsociadoService.php
- database/migrations/2024_07_05_171751_create_descuento_asociados_table.php
> descuentos

- app/Services/AtencionUsuarios/ConvenioService.php
> CentavosBugFix2

- app/Models/Letra.php
- app/Services/AtencionUsuarios/ConvenioService.php
- database/migrations/2024_09_02_185501_create_letras_table.php
Se agrego el atributo numero de letra a la tabla de letra
> convenioActualizacionAtributos

- app/Http/Controllers/Api/ConceptoAplicableController.php
- routes/api/caja/concepto.php
BugFix Carpeta ControllerConceptoAplicable
> ConceptoAplicableBugFix

- app/Http/Controllers/Api/TipoTomaAplicableController.php
- app/Http/Requests/StoreTipoTomaAplicableRequest.php
- app/Http/Resources/TipoTomaAplicableResource.php
- app/Models/AjusteCatalogo.php
- app/Models/ConvenioCatalogo.php
- app/Models/DescuentoCatalogo.php
- app/Models/TipoTomaAplicable.php
- app/Services/Toma/TipoTomaAplicableService.php
- routes/api/catalogos/tomas.php
Tipos de tomas aplicables a ciertos procesos, Api´s generales y sus rutas
> TipoTomaAplicableApi

- app/Http/Controllers/Api/MultaController.php
- app/Http/Requests/StoreMultaRequest.php
- app/Http/Requests/UpdateMultaRequest.php
- app/Http/Resources/MultaResource.php
- app/Models/Multa.php
- app/Services/AtencionUsuarios/MultaService.php
- app/Services/Catalogos/MultaCatalogoService.php
- routes/api/usuarios/multas.php
controller, resource, requests, service y rutas de multas. También se modifico una relación del catalogo de multas
> Multas y modificación de una relación del catalogo de multas

- app/Http/Controllers/Api/ConstanciaController.php
- app/Services/AtencionUsuarios/ConstanciaService.php
- routes/api/catalogos/constancia.php
> ConstanciasVer6

- app/Services/AtencionUsuarios/DescuentoAsociadoService.php
- database/migrations/2024_07_05_171751_create_descuento_asociados_table.php
quite el unique de la curp en la migracion
> descuento, unique de la curp

- app/Services/AtencionUsuarios/ConvenioService.php
Se elimina la conciliacion de estados de pagos de la cancelacion automatica
> BugFixCancelaAutoConve

- app/Providers/AppServiceProvider.php
- app/Services/AtencionUsuarios/ConvenioService.php
- app/Services/AtencionUsuarios/DescuentoAsociadoService.php
> BugFixConvenioDescuento

- app/Services/AtencionUsuarios/DescuentoAsociadoService.php
Se añadio un mejor criterio a la busqueda de los cargos en el registro de descuentos
> MejoraCargaDescuentos

- app/Services/AtencionUsuarios/ConvenioService.php
> ConvenioHotFix
